FROM rockylinux:9

ARG RUBY_VERSION=2.4.4
ARG ASSET_VERSION=local_build
ARG GREP_EXCLUDE='(ld.so|ld-linux-x86-64.so|libBrokenLocale.so|libSegFault.so|libanl.so|libc.so|libdl.so|libm.so|libmvec.so|libnss_compat.so|libnss_dns.so|libnss_files.so|libpthread.so|libresolv.so|librt.so|libthread_db.so|libutil.so|vdso.so)'


RUN dnf update -y && dnf groupinstall -y "Development Tools"
RUN dnf install dnf-plugins-core
RUN dnf repolist --all
RUN dnf config-manager --set-enabled crb
RUN dnf install -y perl

RUN curl -L https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1s.tar.gz -o OpenSSL_1_1_1s.tar.gz && \
  tar -xzvf OpenSSL_1_1_1s.tar.gz && cd openssl-OpenSSL_1_1_1s && \
  ./config --prefix=$(readlink -f ../install) --openssldir=$(readlink -f ../install/ssl) && \
  INSTALL_PREFIX=$(readlink -f ../install) make && \
  INSTALL_PREFIX=$(readlink -f ../install) make install

RUN curl -L https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz -o ruby-install-0.7.0.tar.gz && \
  tar -xzvf ruby-install-0.7.0.tar.gz && \
  cd ruby-install-0.7.0/ && \
  make install && \
  ruby-install ruby ${RUBY_VERSION} -- --with-openssl-dir=$(readlink -f ../install) --enable-load-relative --disable-install-doc && \
  PATH=$PATH:/opt/rubies/ruby-${RUBY_VERSION}/bin/ && export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt && gem install --no-ri --no-rdoc ffi sys-filesystem 

RUN LIBS=$(find /opt/rubies/ruby-${RUBY_VERSION} -type f -executable -exec ldd {} 2>/dev/null \;|  grep "=>" | egrep -v ${GREP_EXCLUDE} | awk '{print $3}'| sort -u ) && \
  for f in $LIBS; do if [ -e $f ]; then echo "Copying Library: $f" && cp $f /opt/rubies/ruby-${RUBY_VERSION}/lib/; fi; done

RUN mkdir /assets/ && \
  export SENSU_ASSET="/assets/sensu-ruby-runtime_${ASSET_VERSION}_ruby-${RUBY_VERSION}_$(source /etc/os-release && echo $ID$VERSION_ID)_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.tar.gz" && \
  tar -czf $SENSU_ASSET -C /opt/rubies/ruby-${RUBY_VERSION}/ .

ENV PATH=$PATH:/opt/rubies/ruby-${RUBY_VERSION}/bin
